In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
X = df.drop('sales', axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
X.shape

(200, 3)

In [9]:
poly_features.sh

(200, 19)

In [10]:
from sklearn.model_selection import  train_test_split


In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
X_train.shape

(140, 19)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler()

In [16]:
X_train = scaler.transform(X_train)

In [17]:
X_test = scaler.transform(X_test)

In [18]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [19]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [20]:
from sklearn.linear_model import Ridge

In [22]:
ridget_model = Ridge(alpha=10)

In [23]:
ridget_model.fit(X_train,y_train)

Ridge(alpha=10)

In [24]:
test_predictions = ridget_model.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [28]:
MAE = mean_absolute_error(y_test,test_predictions)

In [29]:
MAE

0.5774404204714175

In [32]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [33]:
RMSE

0.8946386461319681

In [36]:
from sklearn.linear_model import RidgeCV

In [40]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0))

In [41]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV()

In [42]:
ridge_cv_model.alpha_

0.1

In [52]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [53]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [54]:
ridge_cv_model.alpha_

0.1

In [55]:
test_predictions = ridge_cv_model.predict(X_test)

In [56]:
MAE = mean_absolute_error(y_test,test_predictions)

In [57]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [58]:
MAE

0.42737748843675194

In [59]:
RMSE

0.6180719926956963

In [60]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [61]:
ridge_cv_model.best_score_

-0.3749223340292957

LASSO

In [62]:
from sklearn.linear_model import LassoCV

In [78]:
lasso_cv_model = LassoCV(eps=0.001,n_alphas=100,cv=5)

In [80]:
lasso_cv_model.fit(X_train,y_train)

c:\Users\alamg\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.870e+00, tolerance: 3.684e-01
  model = cd_fast.enet_coordinate_descent(


LassoCV(cv=5)

In [81]:
lasso_cv_model.alpha_

0.004943070909225827

In [82]:
test_predictions = lasso_cv_model.predict(X_test)

In [83]:
MAE = mean_absolute_error(y_test,test_predictions)

In [84]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [85]:
MAE

0.4405488591537115

In [86]:
RMSE

0.6181813495739876

In [87]:
lasso_cv_model.coef_

array([ 4.56928806,  0.07566819,  0.18172079, -4.48979135,  4.59067331,
       -0.20804764, -0.        ,  0.09546681,  0.        ,  1.54242764,
       -0.85370412, -0.        ,  0.09038227, -0.        , -0.        ,
        0.        ,  0.        ,  0.        , -0.        ])

In [88]:
from sklearn.linear_model import ElasticNetCV

In [89]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001,n_alphas=100,max_iter=1000000)

In [90]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [91]:
elastic_model.l1_ratio_

1.0

In [92]:
elastic_model.alpha_

0.004943070909225827

In [93]:
test_predictions = elastic_model.predict(X_test)

In [94]:
MAE = mean_absolute_error(y_test,test_predictions)

In [95]:
MAE

0.4335034618590069